# Generated by Django 3.2.3 on 2021-06-21 09:33

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='action_background_image',
            field=models.ForeignKey(blank=True, help_text='the background image of action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='action_link',
            field=models.CharField(blank=True, help_text='the link of action', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='action_text',
            field=models.CharField(blank=True, help_text='the text of action', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefit_text',
            field=models.CharField(blank=True, help_text='the text of benefit', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefit_title',
            field=models.CharField(blank=True, help_text='the title of benefit', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_background_image',
            field=models.ForeignKey(blank=True, help_text='the background image of action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_now_link',
            field=models.CharField(blank=True, help_text='the link of action', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_now_text',
            field=models.CharField(blank=True, help_text='the text of action', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Write some promotional copy', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_title',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='explore_courses_text',
            field=models.CharField(blank=True, help_text='Write some promotional copy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='explore_courses_title',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_image',
            field=models.ForeignKey(blank=True, help_text='Featured image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_1_icon_name',
            field=models.CharField(blank=True, help_text='https://fontawesome.com/v4.7/icons/', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_1_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_1_title',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_2_icon_name',
            field=models.CharField(blank=True, help_text='https://fontawesome.com/v4.7/icons/', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_2_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_2_title',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_3_icon_name',
            field=models.CharField(blank=True, help_text='https://fontawesome.com/v4.7/icons/', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_3_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_3_title',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta',
            field=models.CharField(default='', help_text='Text to display on Call to Action', max_length=255, verbose_name='Hero CTA'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_link',
            field=models.ForeignKey(blank=True, help_text='Choose a page to link to for the Call to Action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Hero CTA link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_text',
            field=models.CharField(default='', help_text='Write an introduction for the bakery', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Homepage image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='more_courses_link',
            field=models.CharField(blank=True, help_text='the link of more courses', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='more_courses_text',
            field=models.CharField(blank=True, help_text='the text of more courses', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reason_1_icon_name',
            field=models.CharField(blank=True, help_text='https://fontawesome.com/v4.7/icons/', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reason_1_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reason_1_title',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reason_2_icon_name',
            field=models.CharField(blank=True, help_text='https://fontawesome.com/v4.7/icons/', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reason_2_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reason_2_title',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reason_3_icon_name',
            field=models.CharField(blank=True, help_text='https://fontawesome.com/v4.7/icons/', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reason_3_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='reason_3_title',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_1_category',
            field=models.CharField(blank=True, help_text='the category name of first recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_1_image',
            field=models.ForeignKey(blank=True, help_text='the image of first recommended course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_1_link',
            field=models.CharField(blank=True, help_text='the link of first recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_1_name',
            field=models.CharField(blank=True, help_text='the display name of first recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_1_price',
            field=models.CharField(blank=True, help_text='the price of first recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_2_category',
            field=models.CharField(blank=True, help_text='the category name of second recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_2_image',
            field=models.ForeignKey(blank=True, help_text='the image of second recommended course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_2_link',
            field=models.CharField(blank=True, help_text='the link of second recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_2_name',
            field=models.CharField(blank=True, help_text='the display name of second recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_2_price',
            field=models.CharField(blank=True, help_text='the price of second recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_3_category',
            field=models.CharField(blank=True, help_text='the category name of third recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_3_image',
            field=models.ForeignKey(blank=True, help_text='the image of third recommended course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_3_link',
            field=models.CharField(blank=True, help_text='the link of third recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_3_name',
            field=models.CharField(blank=True, help_text='the display name of third recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_3_price',
            field=models.CharField(blank=True, help_text='the price of third recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_4_category',
            field=models.CharField(blank=True, help_text='the category name of fourth recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_4_image',
            field=models.ForeignKey(blank=True, help_text='the image of fourth recommended course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_4_link',
            field=models.CharField(blank=True, help_text='the link of fourth recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_4_name',
            field=models.CharField(blank=True, help_text='the display name of fourth recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_4_price',
            field=models.CharField(blank=True, help_text='the price of fourth recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_5_category',
            field=models.CharField(blank=True, help_text='the category name of fifth recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_5_image',
            field=models.ForeignKey(blank=True, help_text='the image of fifth recommended course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_5_link',
            field=models.CharField(blank=True, help_text='the link of fifth recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_5_name',
            field=models.CharField(blank=True, help_text='the display name of fifth recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_5_price',
            field=models.CharField(blank=True, help_text='the price of fifth recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_6_category',
            field=models.CharField(blank=True, help_text='the category name of sixth recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_6_image',
            field=models.ForeignKey(blank=True, help_text='the image of sixth recommended course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_6_link',
            field=models.CharField(blank=True, help_text='the link of sixth recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_6_name',
            field=models.CharField(blank=True, help_text='the display name of sixth recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_6_price',
            field=models.CharField(blank=True, help_text='the price of sixth recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_7_category',
            field=models.CharField(blank=True, help_text='the category name of seventh recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_7_image',
            field=models.ForeignKey(blank=True, help_text='the image of seventh recommended course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_7_link',
            field=models.CharField(blank=True, help_text='the link of seventh recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_7_name',
            field=models.CharField(blank=True, help_text='the display name of seventh recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_7_price',
            field=models.CharField(blank=True, help_text='the price of seventh recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_8_category',
            field=models.CharField(blank=True, help_text='the category name of eighth recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_8_image',
            field=models.ForeignKey(blank=True, help_text='the image of eighth recommended course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_8_link',
            field=models.CharField(blank=True, help_text='the link of eighth recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_8_name',
            field=models.CharField(blank=True, help_text='the display name of eighth recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recommended_course_8_price',
            field=models.CharField(blank=True, help_text='the price of eighth recommended course', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_cover_image',
            field=models.ForeignKey(blank=True, help_text='the background image of action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_link',
            field=models.CharField(blank=True, help_text='the link of video', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='welcome_text',
            field=models.CharField(blank=True, help_text='Write some promotional copy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='welcome_title',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='what_we_offer_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Write some promotional copy', null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='what_we_offer_title',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_us_text',
            field=models.CharField(blank=True, help_text='the text of why us', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_us_title',
            field=models.CharField(blank=True, help_text='the title of why us', max_length=255, null=True),
        ),
    ]
